students:
    resource: "@StudentsBundle/Resources/config/routing.php"
    prefix:   /

about:
    resource: "@AboutBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
